### ISSUE TITLE
.gitmodules is missing

### ISSUE THREAD

**Issue by MCMic** [BlackBulletIV/super-space-invader#1]
It seems the .gitmodules file is missing or something, «git submodule init» fails to fetch the libs with the error:
No submodule mapping found in .gitmodules for path 'lib/ammo'

**Comment by mebens** [comment]
Should work now. Thanks.

**Comment by MCMic** [comment]
It works, thanks.
Good game. Managed to play it on love 0.9.1 by removing calls to «setLinearDamping». (Debian packs love 0.9.1).
