### ISSUE TITLE
add README.md

### ISSUE THREAD

**Issue by axet** [BlackBulletIV/super-space-invader#2]
Add README.md to the project with youtube refference to the game.

It is amazing!

https://www.youtube.com/watch?v=EJcOuhmAOVs

**Comment by mebens** [comment]
Hey thanks very much for the review (assuming you made it). Never had anything like that for my Ludum Dare submissions.

Will add a README soon.

**Comment by axet** [comment]
I hope to see all great work will be property commented. At least on main page of the project. Also this review looking great.

It is not my review. But no one gonna complain if you add to the main source code a readme with simple game description, installation instructions and game tutorial. As well as live (youtube) demo!

Have fun!
