### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by akien-mga** [BlackBulletIV/super-space-invader#3]
Hi and thanks for your game, it's pretty cool. I'm working on packaging it for Mageia to make it easily installable.

Could you add a LICENSE.txt or LICENSE.md or similar file to specify the license of the code and assets in this repo? According to this thread it seems you chose zlib/libpng, but it's not "official" yet in the repo as far as I can see: https://love2d.org/forums/viewtopic.php?f=5&t=81390&sid=7a26e56000a85b6ea0016d24a6be5c35&start=10#p192149

**Comment by mebens** [comment]
That's nice to hear. I've added the zlib licence to the repo.
