### ISSUE TITLE
Game icon

### ISSUE THREAD

**Issue by akien-mga** [BlackBulletIV/super-space-invader#4]
The minimalistic assets don't really allow to make an icon easily, but in case you have an idea... As I'm packaging the game for a Linux distribution (Mageia), I'd like to have an icon (ideally square and in vector graphics, but anything down to 48x48 should be ok too) for the .desktop file in the menu.

**Comment by mebens** [comment]
I've made a makeshift 56x56 icon and added it to assets/images. It's not all that good, but it's something to go on I suppose.

**Comment by akien-mga** [comment]
Thanks! I used it for my package, it looks fine :)
56x56 is not particularly standard, so I made a custom 64x64 icon with the 56x56 centered in it.

The standard icon sizes in the "hicolor" theme that most Linux distros rely on are:

```
$ ls /usr/share/icons/hicolor/
1024x1024/  16x16/    22x22/  256x256/  32x32/  48x48/    64x64/  8x8/    icon-theme.cache  scalable/
128x128/    192x192/  24x24/  26x26/    36x36/  512x512/  72x72/  96x96/  index.theme       symbolic/
```

(scalable being for SVG, symbolic I have no idea :p)

**Comment by akien-mga** [comment]
For the reference if another packager comes around, here are the build instructions I'm using for super-space-invader (as for all löve2d games it's pretty straight-forward :)): http://svnweb.mageia.org/packages/cauldron/super-space-invader/current/SPECS/super-space-invader.spec?view=markup
